openapi: 3.0.3
info:
  title: STD24059 - TD2
  version: 1.0.0
paths:
  /users:
    get:
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          schema:
            type: integer
            example: 20
      responses:
        200:
          description: liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      example: alice@example.com
        400:
          description: mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters